# Generated by Django 6.0.5 on 2026-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debate",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
